deployment:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json; chown -R 65532: /data"]
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
      volumeMounts:
        - name: data
          mountPath: /data

podDisruptionBudget:
  enabled: false

ingressClass:
  enabled: false

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true

logs:
  general:
    level: DEBUG
  access:
    enabled: true
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: drop

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

additionalArguments:
  - "--api.insecure=true"
  - "--api.dashboard=true"

ports:
  traefik:
    port: 9000
    expose: false
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    redirectTo: 
      port: websecure
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
  metrics:
    port: 9100
    expose: true
    exposedPort: 9100
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data

certResolvers:
  le:
    email: david.blaskow@traefik.io
    tlsChallenge: true
    storage: /data/acme.json

