---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-tls
  namespace: observability
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.${CLUSTERNAME}.demo.traefiklabs.tech`)
      services:
        - name: prometheus-stack-grafana
          port: 80
  tls: 
    certResolver: letsencrypt