grafana:
  enabled: false

prometheus:
  enabled: false

loki:
  enabled: true
  isDefault: false
  config:
    query_scheduler:
      max_outstanding_requests_per_tenant: 2048
    query_range:
      parallelise_shardable_queries: false
      split_queries_by_interval: 0
