additionalPrometheusRules:
  - name: traefik-percentile
    groups:
      - name: general
        rules:
        - record: job:http_duration_seconds:p99:5m
          expr: histogram_quantile(0.99, sum(rate(http_duration_seconds_bucket[5m])) by (job, le))
        - record: job:http_duration_seconds:p90:5m
          expr: histogram_quantile(0.90, sum(rate(http_duration_seconds_bucket[5m])) by (job, le))
        - record: job:http_duration_seconds:p50:5m
          expr: histogram_quantile(0.50, sum(rate(http_duration_seconds_bucket[5m])) by (job, le))

grafana:
  adminPassword: traefik
  dashboardProviders:
   dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: "grafana-traefik-dashboard"

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'traefik'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - traefik
      relabel_configs:
        # Only scape pods with annotation containo.us/monitoring_enable: "true".
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
        # Use port given in annotation containo.us/monitoring_port.
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
        # Add the version label extracted from the pod label version.
      - source_labels: [__meta_kubernetes_pod_label_version]
        action: replace
        replacement: $1
        target_label: version